### ISSUE TITLE
Short_Hair_Dreads_02 plotted on top of beard

### ISSUE THREAD

**Issue by steininge** [kebu/py-avataaars#3]
Hi, 

when Top=Short_Hair_Dreads_02 and facial hair=Beard_x, The hair in the neck is plottet on top of the beard, which does not look right. 
![image](https://user-images.githubusercontent.com/16856185/86951285-971d1a00-c151-11ea-9981-b6ef89af243c.png)

Cheers,
Stein

**Comment by steininge** [comment]
WinterHat1 and 2 could probably be over the beard.
![image](https://user-images.githubusercontent.com/16856185/86958611-b8373800-c15c-11ea-8286-9fec6877fadb.png)

**Comment by kebu** [comment]
Same behaviour in source repository ;)

**Comment by steininge** [comment]
Ok, thanks!
